
drop view if exists adult_50k.v_t1_adult_data_target;

create view adult_50k.v_t1_adult_data_target as
    select id,
           case when target = '>50K' then 1 else 0 end as target
    from adult_50k.adult_data;

drop view if exists adult_50k.v_t1_adult_data_dataset;

create view adult_50k.v_t1_adult_data_dataset as
    select id,
           age,
           case when workclass = 'Federal-gov' then 1 else 0 end as workclass_fg,
           case when workclass = 'Local-gov' then 1 else 0 end as workclass_lg,
           case when workclass = 'Never-worked' then 1 else 0 end as workclass_nw,
           case when workclass = 'Private' then 1 else 0 end as workclass_p,
           case when workclass = 'Self-emp-inc' then 1 else 0 end as workclass_sei,
           case when workclass = 'Self-emp-not-inc' then 1 else 0 end as workclass_seni,
           case when workclass = 'State-gov' then 1 else 0 end as workclass_g,
           case when workclass = 'Without-pay' then 1 else 0 end as workclass_wp,
           fnlwgt,
           education_num,
           case when marital_status = 'Divorced' then 1 else 0 end as marital_status_d,
           case when marital_status = 'Married-AF-spouse' then 1 else 0 end as marital_status_mas,
           case when marital_status = 'Married-civ-spouse' then 1 else 0 end as marital_status_mcs,
           case when marital_status = 'Married-spouse-absent' then 1 else 0 end as marital_status_msa,
           case when marital_status = 'Never-married' then 1 else 0 end as marital_status_nm,
           case when marital_status = 'Separated' then 1 else 0 end as marital_status_s,
           case when marital_status = 'Widowed' then 1 else 0 end as marital_status_w,
           case when occupation = 'Adm-clerical' then 1 else 0 end as occupation_ac,
           case when occupation = 'Armed-Forces' then 1 else 0 end as occupation_af,
           case when occupation = 'Craft-repair' then 1 else 0 end as occupation_cr,
           case when occupation = 'Exec-managerial' then 1 else 0 end as occupation_em,
           case when occupation = 'Farming-fishing' then 1 else 0 end as occupation_fs,
           case when occupation = 'Handlers-cleaners' then 1 else 0 end as occupation_hc,
           case when occupation = 'Machine-op-inspct' then 1 else 0 end as occupation_moi,
           case when occupation = 'Other-service' then 1 else 0 end as occupation_os,
           case when occupation = 'Priv-house-serv' then 1 else 0 end as occupation_phs,
           case when occupation = 'Prof-specialty' then 1 else 0 end as occupation_ps,
           case when occupation = 'Protective-serv' then 1 else 0 end as occupation_pts,
           case when occupation = 'Sales' then 1 else 0 end as occupation_s,
           case when occupation = 'Tech-support' then 1 else 0 end as occupation_ts,
           case when occupation = 'Transport-moving' then 1 else 0 end as occupation_tm,
           case when relationship = 'Husband' then 1 else 0 end as relationship_h,
           case when relationship = 'Own-child' then 1 else 0 end as relationship_oc,
           case when relationship = 'Wife' then 1 else 0 end as relationship_w,
           case when relationship = 'Not-in-family' then 1 else 0 end as relationship_nif,
           case when relationship = 'Unmarried' then 1 else 0 end as relationship_u,
           case when relationship = 'Other-relative' then 1 else 0 end as relationship_or,
           case when race = 'Black' then 1 else 0 end as race_b,
           case when race = 'Asian-Pac-Islander' then 1 else 0 end as race_api,
           case when race = 'Amer-Indian-Eskimo' then 1 else 0 end as race_aie,
           case when race = 'Other' then 1 else 0 end as race_o,
           case when race = 'White' then 1 else 0 end as race_w,
           case when sex = 'Female' then 1 else 0 end as sex_f,
           case when sex = 'Male' then 1 else 0 end as sex_m,
           capital_gain,
           capital_loss,
           hours_per_week,
           case when native_country = 'Cambodia' then 1 else 0 end as native_country_01,
           case when native_country = 'Canada' then 1 else 0 end as native_country_02,
           case when native_country = 'China' then 1 else 0 end as native_country_03,
           case when native_country = 'Columbia' then 1 else 0 end as native_country_04,
           case when native_country = 'Cuba' then 1 else 0 end as native_country_05,
           case when native_country = 'Dominican-Republic' then 1 else 0 end as native_country_06,
           case when native_country = 'Ecuador' then 1 else 0 end as native_country_07,
           case when native_country = 'El-Salvador' then 1 else 0 end as native_country_08,
           case when native_country = 'England' then 1 else 0 end as native_country_09,
           case when native_country = 'France' then 1 else 0 end as native_country_10,
           case when native_country = 'Germany' then 1 else 0 end as native_country_11,
           case when native_country = 'Greece' then 1 else 0 end as native_country_12,
           case when native_country = 'Guatemala' then 1 else 0 end as native_country_13,
           case when native_country = 'Haiti' then 1 else 0 end as native_country_14,
           case when native_country = 'Holand-Netherlands' then 1 else 0 end as native_country_15,
           case when native_country = 'Honduras' then 1 else 0 end as native_country_16,
           case when native_country = 'Hong' then 1 else 0 end as native_country_17,
           case when native_country = 'Hungary' then 1 else 0 end as native_country_18,
           case when native_country = 'India' then 1 else 0 end as native_country_19,
           case when native_country = 'Iran' then 1 else 0 end as native_country_20,
           case when native_country = 'Ireland' then 1 else 0 end as native_country_21,
           case when native_country = 'Italy' then 1 else 0 end as native_country_22,
           case when native_country = 'Jamaica' then 1 else 0 end as native_country_23,
           case when native_country = 'Japan' then 1 else 0 end as native_country_24,
           case when native_country = 'Laos' then 1 else 0 end as native_country_25,
           case when native_country = 'Mexico' then 1 else 0 end as native_country_26,
           case when native_country = 'Nicaragua' then 1 else 0 end as native_country_27,
           case when native_country = 'Outlying-US(Guam-USVI-etc)' then 1 else 0 end as native_country_28,
           case when native_country = 'Peru' then 1 else 0 end as native_country_29,
           case when native_country = 'Philippines' then 1 else 0 end as native_country_30,
           case when native_country = 'Poland' then 1 else 0 end as native_country_31,
           case when native_country = 'Portugal' then 1 else 0 end as native_country_32,
           case when native_country = 'Puerto-Rico' then 1 else 0 end as native_country_33,
           case when native_country = 'Scotland' then 1 else 0 end as native_country_34,
           case when native_country = 'South' then 1 else 0 end as native_country_35,
           case when native_country = 'Taiwan' then 1 else 0 end as native_country_36,
           case when native_country = 'Thailand' then 1 else 0 end as native_country_37,
           case when native_country = 'Trinadad&Tobago' then 1 else 0 end as native_country_38,
           case when native_country = 'United-States' then 1 else 0 end as native_country_39,
           case when native_country = 'Vietnam' then 1 else 0 end as native_country_40,
           case when native_country = 'Yugoslavia' then 1 else 0 end as native_country_41
    from adult_50k.adult_data;


drop view if exists adult_50k.v_t1_adult_test_target;

create view adult_50k.v_t1_adult_test_target as
    select id,
           case when target = '>50K' then 1 else 0 end as target
    from adult_50k.adult_test;

drop view if exists adult_50k.v_t1_adult_test_dataset;

create view adult_50k.v_t1_adult_test_dataset as
    select id,
           age,
           case when workclass = 'Federal-gov' then 1 else 0 end as workclass_fg,
           case when workclass = 'Local-gov' then 1 else 0 end as workclass_lg,
           case when workclass = 'Never-worked' then 1 else 0 end as workclass_nw,
           case when workclass = 'Private' then 1 else 0 end as workclass_p,
           case when workclass = 'Self-emp-inc' then 1 else 0 end as workclass_sei,
           case when workclass = 'Self-emp-not-inc' then 1 else 0 end as workclass_seni,
           case when workclass = 'State-gov' then 1 else 0 end as workclass_g,
           case when workclass = 'Without-pay' then 1 else 0 end as workclass_wp,
           fnlwgt,
           education_num,
           case when marital_status = 'Divorced' then 1 else 0 end as marital_status_d,
           case when marital_status = 'Married-AF-spouse' then 1 else 0 end as marital_status_mas,
           case when marital_status = 'Married-civ-spouse' then 1 else 0 end as marital_status_mcs,
           case when marital_status = 'Married-spouse-absent' then 1 else 0 end as marital_status_msa,
           case when marital_status = 'Never-married' then 1 else 0 end as marital_status_nm,
           case when marital_status = 'Separated' then 1 else 0 end as marital_status_s,
           case when marital_status = 'Widowed' then 1 else 0 end as marital_status_w,
           case when occupation = 'Adm-clerical' then 1 else 0 end as occupation_ac,
           case when occupation = 'Armed-Forces' then 1 else 0 end as occupation_af,
           case when occupation = 'Craft-repair' then 1 else 0 end as occupation_cr,
           case when occupation = 'Exec-managerial' then 1 else 0 end as occupation_em,
           case when occupation = 'Farming-fishing' then 1 else 0 end as occupation_fs,
           case when occupation = 'Handlers-cleaners' then 1 else 0 end as occupation_hc,
           case when occupation = 'Machine-op-inspct' then 1 else 0 end as occupation_moi,
           case when occupation = 'Other-service' then 1 else 0 end as occupation_os,
           case when occupation = 'Priv-house-serv' then 1 else 0 end as occupation_phs,
           case when occupation = 'Prof-specialty' then 1 else 0 end as occupation_ps,
           case when occupation = 'Protective-serv' then 1 else 0 end as occupation_pts,
           case when occupation = 'Sales' then 1 else 0 end as occupation_s,
           case when occupation = 'Tech-support' then 1 else 0 end as occupation_ts,
           case when occupation = 'Transport-moving' then 1 else 0 end as occupation_tm,
           case when relationship = 'Husband' then 1 else 0 end as relationship_h,
           case when relationship = 'Own-child' then 1 else 0 end as relationship_oc,
           case when relationship = 'Wife' then 1 else 0 end as relationship_w,
           case when relationship = 'Not-in-family' then 1 else 0 end as relationship_nif,
           case when relationship = 'Unmarried' then 1 else 0 end as relationship_u,
           case when relationship = 'Other-relative' then 1 else 0 end as relationship_or,
           case when race = 'Black' then 1 else 0 end as race_b,
           case when race = 'Asian-Pac-Islander' then 1 else 0 end as race_api,
           case when race = 'Amer-Indian-Eskimo' then 1 else 0 end as race_aie,
           case when race = 'Other' then 1 else 0 end as race_o,
           case when race = 'White' then 1 else 0 end as race_w,
           case when sex = 'Female' then 1 else 0 end as sex_f,
           case when sex = 'Male' then 1 else 0 end as sex_m,
           capital_gain,
           capital_loss,
           hours_per_week,
           case when native_country = 'Cambodia' then 1 else 0 end as native_country_01,
           case when native_country = 'Canada' then 1 else 0 end as native_country_02,
           case when native_country = 'China' then 1 else 0 end as native_country_03,
           case when native_country = 'Columbia' then 1 else 0 end as native_country_04,
           case when native_country = 'Cuba' then 1 else 0 end as native_country_05,
           case when native_country = 'Dominican-Republic' then 1 else 0 end as native_country_06,
           case when native_country = 'Ecuador' then 1 else 0 end as native_country_07,
           case when native_country = 'El-Salvador' then 1 else 0 end as native_country_08,
           case when native_country = 'England' then 1 else 0 end as native_country_09,
           case when native_country = 'France' then 1 else 0 end as native_country_10,
           case when native_country = 'Germany' then 1 else 0 end as native_country_11,
           case when native_country = 'Greece' then 1 else 0 end as native_country_12,
           case when native_country = 'Guatemala' then 1 else 0 end as native_country_13,
           case when native_country = 'Haiti' then 1 else 0 end as native_country_14,
           case when native_country = 'Holand-Netherlands' then 1 else 0 end as native_country_15,
           case when native_country = 'Honduras' then 1 else 0 end as native_country_16,
           case when native_country = 'Hong' then 1 else 0 end as native_country_17,
           case when native_country = 'Hungary' then 1 else 0 end as native_country_18,
           case when native_country = 'India' then 1 else 0 end as native_country_19,
           case when native_country = 'Iran' then 1 else 0 end as native_country_20,
           case when native_country = 'Ireland' then 1 else 0 end as native_country_21,
           case when native_country = 'Italy' then 1 else 0 end as native_country_22,
           case when native_country = 'Jamaica' then 1 else 0 end as native_country_23,
           case when native_country = 'Japan' then 1 else 0 end as native_country_24,
           case when native_country = 'Laos' then 1 else 0 end as native_country_25,
           case when native_country = 'Mexico' then 1 else 0 end as native_country_26,
           case when native_country = 'Nicaragua' then 1 else 0 end as native_country_27,
           case when native_country = 'Outlying-US(Guam-USVI-etc)' then 1 else 0 end as native_country_28,
           case when native_country = 'Peru' then 1 else 0 end as native_country_29,
           case when native_country = 'Philippines' then 1 else 0 end as native_country_30,
           case when native_country = 'Poland' then 1 else 0 end as native_country_31,
           case when native_country = 'Portugal' then 1 else 0 end as native_country_32,
           case when native_country = 'Puerto-Rico' then 1 else 0 end as native_country_33,
           case when native_country = 'Scotland' then 1 else 0 end as native_country_34,
           case when native_country = 'South' then 1 else 0 end as native_country_35,
           case when native_country = 'Taiwan' then 1 else 0 end as native_country_36,
           case when native_country = 'Thailand' then 1 else 0 end as native_country_37,
           case when native_country = 'Trinadad&Tobago' then 1 else 0 end as native_country_38,
           case when native_country = 'United-States' then 1 else 0 end as native_country_39,
           case when native_country = 'Vietnam' then 1 else 0 end as native_country_40,
           case when native_country = 'Yugoslavia' then 1 else 0 end as native_country_41
    from adult_50k.adult_test;